// web3 is an Ethereum client library
const { Web3, WebSocketProvider} = require('web3');
// Set up a connection to the Ganache network
const web3 = new Web3(new WebSocketProvider('ws://localhost:7545'));

web3.eth.getBlockNumber().then((result) => {
    console.log("Latest Ethereum Block is ",result);
});

// This file is generated by the Solidity compiler to easily interact with
// the contract using the web3 library.
const loginAbi = require('../solidity/build/contracts/Login.json').abi;
const LoginContract = new web3.eth.Contract(loginAbi,'0x85f83D667d3332a530B3642641e0AB7160ae02fC');

module.exports = LoginContract;